spring:
    profiles:
        active:
            - production
        include: 
            - common
logging:
  file: logs/elsevier_test_production.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ROOT: INFO
    com.elsevier.test : INFO